name: Docker Build and GitOps Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}

    - name: Checkout GitOps repo
      uses: actions/checkout@v2
      with:
        repository: plentifullee/gitops
        token: ${{ secrets.GITOPS_PAT }}
        path: gitops

    - name: Update image tag in GitOps repo
      run: |
        cd gitops/app
        sed -i "s|image: .*/flask-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}|" flask.yaml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add flask.yaml
        git commit -m "Update flask-app image to ${{ github.sha }}"
        git push
